question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "General Knowledge",
     "question": "Pluto is a planet.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
                                      "question": "Waluigi&#039;s first appearance was in what game?",
                                      "correct_answer": "Mario Tennis 64 (N64)",
                                      "incorrect_answers": ["Wario Land: Super Mario Land 3", "Mario Party (N64)",
                                                            "Super Smash Bros. Ultimate"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge", "question": "What is a Burgee?",
     "correct_answer": "A flag", "incorrect_answers": ["A rope", "A window", "A type of food"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "Which slogan did the fast food company, McDonald&#039;s, use before their &quot;I&#039;m Lovin&#039; It&quot; slogan?",
     "correct_answer": "We Love to See You Smile",
     "incorrect_answers": ["Why Pay More!?", "Have It Your Way", "Making People Happy Through Food"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "What does the &#039;S&#039; stand for in the abbreviation SIM, as in SIM card? ",
     "correct_answer": "Subscriber", "incorrect_answers": ["Single", "Secure", "Solid"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "Where did the pineapple plant originate?", "correct_answer": "South America",
     "incorrect_answers": ["Hawaii", "Europe", "Asia"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "Who is depicted on the US hundred dollar bill?", "correct_answer": "Benjamin Franklin",
     "incorrect_answers": ["George Washington", "Abraham Lincoln", "Thomas Jefferson"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]

